# Generated by Django 6.0.5 on 2026-05-12 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderTransaction',
            fields=[
                ('Order_id', models.IntegerField(primary_key=True, serialize=False)),
                ('User_id', models.IntegerField()),
                ('Order_date', models.DateTimeField(auto_now_add=True)),
                ('Item_name', models.CharField(max_length=200)),
                ('Order_qty', models.IntegerField()),
                ('Unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Delivery_address', models.CharField(max_length=300)),
            ],
        ),
    ]
